### ISSUE TITLE
Cannot access USB printer under Ubuntu 20.04

### ISSUE THREAD

**Issue by hadmut** [glasen/snap-cura#3]
Hi, 
even after 
snap connect cura-slicer:mount-observe
snap connect cura-slicer:removable-media
as recommended on https://snapcraft.io/cura-slicer
the snap version still can't detect an USB printer under Ubuntu 20.04. Instead, the kernel issues error messages like

Aug 17 20:49:37 pc kernel: [ 8721.055150] audit: type=1400 audit(1629226177.364:694): apparmor="DENIED" operation="open" profile="snap.cura-slicer.cura" name="/sys/devices/pnp0/00:04/id" pid=57119 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Aug 17 20:49:37 pc kernel: [ 8721.055484] audit: type=1400 audit(1629226177.364:695): apparmor="DENIED" operation="open" profile="snap.cura-slicer.cura" name="/sys/devices/pci0000:00/0000:00:01.3/0000:01:00.0/usb1/1-4/bNumInterfaces" pid=57119 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

(the older cura version coming with ubuntu as a regular ubuntu package can, so it's not a printer or usb settings problem.)

**Comment by matthewbaggett** [comment]
While researching an unrelated issue, I also had this issue recently trying to talk directly to a USB printer.

**Comment by glasen** [comment]
Sorry for the very late answer. I completely stuck at work and didn't see your issue.

I've added the "raw-usb"-interface to the snap package. You have to activate is manually:
`
snap connect cura-slicer:raw-usb`

This should fix your problem.

**Comment by hadmut** [comment]
Thanks for dealing with that. 

But still not working, even after updating and snap connect I do get lots of AppArmor error messsages about snap,cura-slicer prohibited opening /sys/devices/pnp0/00:04/id and printer not starting.

**Comment by hadmut** [comment]
I've opened a bug report for snapd, see 

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1950855

because I'd expect at least better documentation and debugging options from snapd. 

snapd's apparmor structure quite often causes this sort of problems.

**Comment by hadmut** [comment]
After adding a line to the apparmor profile I got somewhat further. Now no apparmor messages anymore, still no printing, but strace revealed that cura is repeatedly trying to 

openat(AT_FDCWD, "/sys/devices/pci0000:00/0000:00:01.3/0000:01:00.0/usb1/1-3/1-3:1.0/ttyUSB0/interface", O_RDONLY|O_CLOEXEC) = -1 ENOENT


where the path seems to be wrong, doesn't exist here.Instead there is 

/sys/devices/pci0000:00/0000:00:01.3/0000:01:00.2/0000:02:04.0/0000:06:00.0/usb3/3-1/3-1:1.0/interface

as the only „interfaces“ in /sys/devices. 

That could be related to having the printer connected to a USB3 port.

**Comment by glasen** [comment]
I just read the launchpad bug entry. Have you removed your changes to Apparmor?

**Comment by hadmut** [comment]
Not yet. Modifying the apparmor settings got mit somewhat further, but it is still not printing with this printer (the older version that comes with ubuntu 20.04 does), so I cannot omit changes to see whether they are required or not. 

Now it looks like cura it its current version can't deal with that printer anymore, and I do suspect that it is either a bug in cura (there's an exception), or the incompatibility with printers of that particular brand, since cura tries to guess the baud rate and not always come to the same result (while the printer, I guess or hope, has always the same). 

I've opened another bug at cura
https://github.com/Ultimaker/Cura/issues/10878#issuecomment-974184617
but they said that they don't offer any support for USB-printing, since their own printers don't use that anymore. 

So I'm somewhat lost and confronted with the problem, that debugging this could cost me more time than I can afford for this. 

Next step would be to install the same version of cura locally without snap and see, whether this problem is snap related (and allowing to modify python code and add some debugging code or remove that baud rate guessing).

**Comment by Johnnii360** [comment]
I want to chime in here too. I have the same issue and added all rights as mentioned. The only way to connect via USB is to run the Appimage as root.

**Comment by hadmut** [comment]
The cura people claim to have found the bug. 

But they also claim, that this bug is not contained in the upstream cura code itself, but brought in by the snap packaging, which applies an erroneous patch. 

See 
https://github.com/Ultimaker/Cura/issues/10878

**Comment by Ghostkeeper** [comment]
The error in question comes from using a string-based regex on a `bytes` object. If the object is `bytes` (and it is, coming from the serial port) then the regex should also be specified as a `bytes` object. With the literals in Python, that means it should use `b" ... "` instead of `r" ... "` (and then make sure that the escape codes are still correct). The patches made for this distribution use `r" ... "`.

I'm not sure why those patches are in place there in the first place. But if they are necessary, I think it'd be as simple as changing the `r` into a `b`.

**Comment by dariuszz123** [comment]
I can confirm both issues with USB 3D printer connection on mint 19.1 (ubuntu 18.04) :

1. apparmor was blocking usb connection so as a workaround i added:

```
/sys/devices/pnp*/*/id mrwklix,
```

to `/var/lib/snapd/apparmor/profiles/snap.cura-slicer.cura` and reloaded apparmor config:
```
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.cura-slicer.cura
```

2. when trying to use 3D printer `monitor` window in cura - `USBPrinterOutputDevice.py` regexp was crashing. As a workaround I'm mounting (overriding) original [USBPrinterOutputDevice.py](https://github.com/Ultimaker/Cura/blob/master/plugins/USBPrinting/USBPrinterOutputDevice.py) to snap package:
```
sudo mount --bind -o nodev,ro /home/darius/USBPrinterOutputDevice.py /snap/cura-slicer/current/usr/lib/cura/plugins/USBPrinting/USBPrinterOutputDevice.py
```

With both modifications cura started successfully communicating with my 3d printer (ender 3 v2).

**Comment by ogra1** [comment]
@glasen got a new printer recently and got finally around to try your cura snap and I'm indeed seeing the same issue over here ... by the looks of it the apparmor denial:
```
audit[3340803]: AVC apparmor="DENIED" operation="open" profile="snap.cura-slicer.cura" name="/sys/devices/pnp0/00:02/id" pid=3340803 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
just talks about *reading* from /sys/devices/pnp* ... the `hardware-observe` interface should grant this, would you mind adding that plug to the snapcraft.yaml for the next release, that should be enough to make this specific one go away (no idea if there will be subsequent denials after this is readable, but that should be the first step ...)

**Comment by glasen** [comment]
@ogra1:

I've just added the interface to the YAML-file. Sorry that it took so long.
